### ISSUE TITLE
大佬，可否适配青龙面板，脚本很好用。

### ISSUE THREAD

**Issue by skyshenma** [seishinkouki/oshwhub_autosign#11]
青龙面板可以定义环境变量，可以订阅脚本。即使源代码更新，文件被覆盖，只要环境变量没改，都可以不用上心是不是还生效的问题。
不过现在使用也脚本非常方便，能适配青龙面板就更加完美了，目前用青龙面板在跑，直接改的脚本文件，往后就怕大佬更新源码了，我还在用旧版的。
感谢大佬开发出这么好用的脚本。

**Comment by seishinkouki** [comment]
适配青龙在进行中, 同时(可能)会有立创商城自动领券功能, 可以等我更新

**Comment by skyshenma** [comment]
太好了，感谢大佬适配，哈哈哈。期待，坐等
