### ISSUE TITLE
无法登录OSHWHub

### ISSUE THREAD

**Issue by YukinoShiratama** [seishinkouki/oshwhub_autosign#3]
登录提示
> 签到结果: 签到结果: 登录失败, 可能原因1:用户密码错误2:登录需要验证
三天奖励结果: 
七天奖励结果:
检查源码后发现嘉立创似乎修改了一些登录参数，oshw_res无法正常获得。

**Comment by seishinkouki** [comment]
最新测试可用, 请尝试将源码中的多处8.8.8.8替换成你的常用登录ip

**Comment by seishinkouki** [comment]
单独将"X-Forwarded-For"拿出来是考虑存在这样的场景, 脚本挂在远程主机上甚至是海外主机上, 这样可以将ip设置自己本地常登陆ip 避免被风控, 如果不需要覆盖的话直接删掉这一项即可, 不需要再去查询ip接口

**Comment by QGB** [comment]
“签到结果: 登录失败, 可能原因1:用户密码错误2:登录需要验证”

**Comment by seishinkouki** [comment]
> “签到结果: 登录失败, 可能原因1:用户密码错误2:登录需要验证”

没看字吗, X-Forwarded-For拿掉就行了

**Comment by QGB** [comment]
@seishinkouki  8.8.8.8 换自己的 IP ，好了，其他没动

 可以在控制台输出 第几次连续签到吗？

**Comment by seishinkouki** [comment]
> @seishinkouki  8.8.8.8 换自己的 IP ，好了，其他没动
> 
>  可以在控制台输出 第几次连续签到吗？

可以实现，可以参考283行自己实现下
