### ISSUE TITLE
登录脚本已经失效

### ISSUE THREAD

**Issue by FSJohn** [seishinkouki/oshwhub_autosign#6]
前天立创更新了接口，尝试多次，发现脚本已经无法登录。

**Comment by seishinkouki** [comment]
确认没有更新, 我的能用, 看下是不是这个问题https://github.com/seishinkouki/oshwhub_autosign/issues/3

**Comment by FSJohn** [comment]
谢谢，问题已经解决。

**Comment by QGB** [comment]
“签到结果: 登录失败, 可能原因1:用户密码错误2:登录需要验证”
