### ISSUE TITLE
大佬，如果想在青龙上使用的话，用户名密码等环境变量应该怎么写？

### ISSUE THREAD

**Issue by shengmean** [seishinkouki/oshwhub_autosign#8]

**Comment by seishinkouki** [comment]
如果是自用的话, 修改代码里面的 ```OSHW``` 变量就行了, 没有必要使用环境变量

**Comment by shengmean** [comment]
好的。之前没有看到360行，设置很久没有设置起来。放在青龙里，有个好处是，即使源代码更新，文件被覆盖，只要环境变量没改，都可以不用上心是不是还生效的问题。青龙不好设的话，能否用OSHW.json的方式？

**Comment by seishinkouki** [comment]
> 好的。之前没有看到360行，设置很久没有设置起来。放在青龙里，有个好处是，即使源代码更新，文件被覆盖，只要环境变量没改，都可以不用上心是不是还生效的问题。青龙不好设的话，能否用OSHW.json的方式？

早期没考虑那么多, 也不知道青龙这个东西, 后面有时间我再更新适配青龙环境

**Comment by shengmean** [comment]
好的，谢谢大佬。。脚本很好用。。
